services:
  aqua-lib:
    container_name: aqua
    hostname: aqua
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ~/.ssh:/root/.ssh
      - /shared-mem:/dev/shm
      - ./start.sh:/start.sh
      - ../../../aqua:/root/aqua
